[build]
  publish = "."

[[headers]]
  for = "/data/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    
[[redirects]]
  from = "/ako-volit"
  to = "/ako-volit.html"
  status = 200

[[redirects]]
  from = "/kandidati"
  to = "/kandidati.html"
  status = 200
